### ISSUE TITLE
Device's name isn't dispalayed properly in Zafira after rerun

### ISSUE THREAD

**Issue by Tamikana** [qaprosoft/carina-demo#1]
After rerun device's name in Zafira isn't changed and displayed as it was after the first run. In logs you can see the right one.
https://drive.google.com/a/qaprosoft.com/file/d/0B78aOxuKRA1ZRlJOaVdCRnhDZlE/view?usp=sharing
https://drive.google.com/a/qaprosoft.com/file/d/0B78aOxuKRA1ZUExmVHhkZkRPNlk/view?usp=sharing

**Comment by vdelendik** [comment]
should be fixed in 5.2.0.x core
