### ISSUE TITLE
Error message is present  in Console log for API-Demo-Test

### ISSUE THREAD

**Issue by okamara** [qaprosoft/carina-demo#110]
Tested via carina-core_version=6.4.37-SNAPSHOT, API-Demo-Test
Steps:
1. Run API-Demo-Test
2. Verify Console log
Actual result: Error message is present 
->
[ERROR] Could not retrieve the last modification timestamp for the URI [http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?wsdl] from the HTTP URL connection. The [Last-Modified] header was probably not set correctly.

**Comment by vdelendik** [comment]
fixed by: https://github.com/qaprosoft/carina-demo/pull/120
test scenario:
launch any test from qaprosoft/carina-demo (branch: master)

**Comment by dhreben** [comment]
Fixed:
Tested (branch: master),API-Demo-Test
<img width="1130" alt="Screen Shot 2020-10-01 at 12 51 41" src="https://user-images.githubusercontent.com/50950954/94794659-de2f4a00-03e4-11eb-8964-4d6df6318821.png">
