### ISSUE TITLE
Test from cucumber-web.xml failed

### ISSUE THREAD

**Issue by DenisPitsul2020** [qaprosoft/carina-demo#127]
Test from cucumber-web.xml failed in carina-demo because of
java.lang.AbstractMethodError: org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(Lorg/apache/logging/log4j/core/config/ConfigurationSource;)Lorg/apache/logging/log4j/core/config/Configuration;
But all steps passes and after that this error appears.
And during creating a project through archetype, the feature/GSMArenaNews.feature doesn’t exist in the project.

**Comment by DenisPitsul2020** [comment]
Resolved by adding log4j-core dependency #128

**Comment by dhreben** [comment]
Fixed
