### ISSUE TITLE
enable auto screenshoting for demo CI pipelines by default

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina-demo#147]
We already have auto-screenshots=true in config files but pipeline jobs are generated with unchecked property...
In demo purposes let's provide option to nmake it enable for web/mobile jobs

**Comment by vdelendik** [comment]
fixed: https://github.com/qaprosoft/carina-demo/pull/152

**Comment by vdelendik** [comment]
During the testing scan carina-demo. Web and mobile tests should have auto_screenshot field enabled for all of them

**Comment by dhreben** [comment]
Verified.
