### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by shivakadu** [qaprosoft/carina-demo#23]
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< com.qaprosoft:carina-demo >----------------------
[INFO] Building Carina Demo 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] Downloading from : https://repo.maven.apache.org/maven2/com/qaprosoft/carina-core/maven-metadata.xml
[INFO] Downloaded from : https://repo.maven.apache.org/maven2/com/qaprosoft/carina-core/maven-metadata.xml (3.4 kB at 5.0 kB/s)
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.9:prepare-agent (default) @ carina-demo ---
[INFO] argLine set to -javaagent:/Users/shiva.ramraokadu/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Users/shiva.ramraokadu/Downloads/carina-demo-master/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ carina-demo ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ carina-demo ---
[INFO] Compiling 13 source files to /Users/shiva.ramraokadu/Downloads/carina-demo-master/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] error: error reading /Users/shiva.ramraokadu/.m2/repository/com/qaprosoft/alice-client/1.1.0/alice-client-1.1.0.jar; zip file is empty
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.064 s
[INFO] Finished at: 2018-09-28T10:28:34+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project carina-demo: Compilation failure
[ERROR] error: error reading /Users/shiva.ramraokadu/.m2/repository/com/qaprosoft/alice-client/1.1.0/alice-client-1.1.0.jar; zip file is empty
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by vdelendik** [comment]
just try to recompile with "-U" flag using command line:
mvn -U clean compile

it should reupload missed dependency
