### ISSUE TITLE
AnnotationTransformer not found

### ISSUE THREAD

**Issue by ampc** [qaprosoft/carina-demo#30]
1. Cloned this repo
2. Executed`mvn clean`
3. Executed api.xml TestNG Suite

```org.testng.TestNGException: 
Listener com.qaprosoft.carina.core.foundation.retry.AnnotationTransformer was not found in project's classpath```

**Comment by vdelendik** [comment]
yesterday new 6.0.0 carina-core generation was released. release notes coming soon.
To be able to switch to new version we had to merge existing 6.0-beta11 branch into the master.

You can pull latest changes from master to be able to run tests on new 6.0 core generation
