### ISSUE TITLE
How to specify multiple browser configuration in TESTNG.xml and have carina pickup those configuration ? Eg: I want to run one script on firefox and one on chrome in two different nodes.

### ISSUE THREAD

**Issue by kannannagasamy** [qaprosoft/carina-demo#48]
I tried adding browser-type to web.xml in the "carina-demo" example and pickup the values in the Test class, But carina is taking browser names from _config.properties file. 

<test name="GSM arena web tests in Chrome">
      **<parameter name="browser-type" value="CHROME"/>**
		<classes>
			<class name="com.qaprosoft.carina.demo.WebSampleTest" />
		</classes>
	</test>

**Comment by vdelendik** [comment]
@kannannagasamy, 
yep, by default carina could start only browser/driver described in global _config.properties.
That's recommended approach to be able to provide valid reporting later.
At the same time IDriverPool provide possibility to start any browser/driver using custom desired capabilities:
default public WebDriver getDriver(String name, DesiredCapabilities capabilities);
default public WebDriver getDriver(String name, DesiredCapabilities capabilities, String seleniumHost);

so you can specify your default chrome driver details in _config.properties but to invoke secondary browser against firefox use such driver startup method:
DesiredCapabilities capabilities = new FirefoxCapabilities().getCapability("ff-capabilities");
getDriver("ff-driver", capabilities);

among supported capabilities classes are:
IECapabilities, ChromeCapabilities, FirefoxCapabilities, OperaCapabilities

In additions you can put set of properties into custom properties file and read them into desired capabilities:
String customCapabilities = "browserstack/android/Samsung_Galaxy_S8.properties"
DesiredCapabilities caps = new CapabilitiesLoader().getCapabilities(customCapabilities);
getDriver("galaxy-s8-driver", caps);
