### ISSUE TITLE
MobileUtils.Tap() method Not Working on iOS

### ISSUE THREAD

**Issue by AherVikasG** [qaprosoft/carina-demo#57]
Hi,

I am trying to click on button by using MobileUtils.tap it executed but doesn't perform any action on device.

inside tap method -
touchAction.press(startPoint).waitAction(waitOptions).release().perform(); is used 
I tried alternative method -          	
touchAction.tap(PointOption.point(startx, starty)).release().perform(); 

But i am getting below exception :- 
org.openqa.selenium.support.events.EventFiringWebDriver cannot be cast to io.appium.java_client.MobileDriver

please help me to resolve it.

**Comment by vdelendik** [comment]
submitted issue in valid project: https://github.com/qaprosoft/carina/issues/706
this one is closed
