### ISSUE TITLE
update web and api tests according to the changes on gsm arena

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina-demo#59]
1. API-Demo-Test: 2 failures due to the 
Expected: a JSON array got: a JSON object org.skyscreamer.jsonassert.JSONAssert.assertEquals(JSONAssert.java:256) co....

2. Web-Demo-Test: 2 failures due to the
Unable to open model: ...

3. Web-Demo-Test: 2 failures due to the
stale element reference: element is not attached to the page document

new version should be fully passed

**Comment by vdelendik** [comment]
fixed. executing api and web tests should be green in carina-demo

**Comment by okamara** [comment]
Tested on jenkins - 5.1-beta3, qps-infra - develop, pipeline - develop.
Executed api and web tests.
Api tests are green, but web demo tests are red
<img width="326" alt="Screen Shot 2020-06-25 at 11 56 08 PM" src="https://user-images.githubusercontent.com/32964663/85794694-b5414e00-b73f-11ea-8f95-cc65960f4f42.png">

**Comment by vdelendik** [comment]
fixed testdata to validate correctly. also pushed changes to carina-archetype so next archetype release should have100% pass rate for web
![image](https://user-images.githubusercontent.com/4551455/85855666-46a3d500-b7bf-11ea-9615-80e6d0c21e4c.png)

**Comment by okamara** [comment]
Tested on qaprosoft/carina-demo. Web tests are passed. Api tests are failed.
<img width="561" alt="Screen Shot 2020-06-29 at 9 41 05 PM" src="https://user-images.githubusercontent.com/32964663/86043403-5f2b1e00-ba51-11ea-93e8-d17dd3350703.png">
<img width="1025" alt="Screen Shot 2020-06-29 at 9 37 06 PM" src="https://user-images.githubusercontent.com/32964663/86043416-64886880-ba51-11ea-973a-8d3a5410d271.png">

**Comment by okamara** [comment]
Reverified. Fixed.
