### ISSUE TITLE
add localization tests into demo

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina-demo#6]
localization and internationalization features should be demoed using demo tests

**Comment by vdelendik** [comment]
merged: https://github.com/qaprosoft/carina-demo/pull/123
during the testing Web-Localization-Demo-Test should be executed vs different locales

**Comment by dhreben** [comment]
Verified.
Web-Localization-Demo-Tests are successfully executed in different locales:

<img width="338" alt="Screen Shot 2020-10-22 at 18 20 01" src="https://user-images.githubusercontent.com/50950954/96893276-352fb880-1493-11eb-852b-11090116bf0a.png">
