### ISSUE TITLE
Pull request jobs run with errors after completed all default steps

### ISSUE THREAD

**Issue by okamara** [qaprosoft/carina-demo#79]
[ERROR] Could not create local repository at /var/jenkins_home/.m2/repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
<img width="1171" alt="Screen Shot 2019-11-26 at 9 28 39 PM" src="https://user-images.githubusercontent.com/32964663/69661625-c768ea00-1093-11ea-82b2-c883e35c47b1.png">

**Comment by ilya-varchenya** [comment]
sudo chown -R your_user:your_user ~/.m2
sudo chmod -R a+rws ~/.m2
./stop.sh
docker-compose rm -fv
./start.sh

**Comment by okamara** [comment]
Can't repro now.
