### ISSUE TITLE
when executing test via Internet Explorer browser, it is not showing consistent behavior.

### ISSUE THREAD

**Issue by prasadjshimpi** [qaprosoft/carina-demo#82]
When executing tests via the Internet Explorer browser, it is not showing consistent behavior.

Sometimes tests run successfully and sometimes it gives below error message. 
**Unexpected error launching Internet Explorer. IELaunchURL() returned HRESULT 80070005 ('Access is denied.') for URL 'http://localhost:40488/'**

Currently using IE 32 bit and IE driver 32bit.

There is an issue of IE slowness type if both of them are not matched.

[web_xml.txt](https://github.com/qaprosoft/carina-demo/files/4005219/web_xml.txt)

**Comment by vdelendik** [comment]
closing as can't repro
