### ISSUE TITLE
provide example of multiply browsers/drivers usage per each test

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina-demo#94]
need simple example howto start 2 browsers per test and manipulate them via different page objects in 2 sessions in parallel

**Comment by vdelendik** [comment]
done: https://github.com/qaprosoft/carina-demo/pull/130/files

**Comment by vdelendik** [comment]
During the testing please scan carina-demo from qaprosoft org and execute Web-Multiple-Browser-Demo-Test job.
2 drivers and video recordings should be displayed in reporting

**Comment by dhreben** [comment]
Verified.
