### ISSUE TITLE
exclude any reference to log4j from demo project

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina-demo#96]
log4j is too old and demo project should migrate to something actual like logback.
after fixing, please submit new ticket to generate carina archetype based on changes

**Comment by vdelendik** [comment]
requirements:
1) exclude old log4j 1.2.17 completely
2) declare latest slf4j interface and update all loggers declaration in demo classes
3) add logback dependency as modern logger implementation
<dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.2.3</version>
</dependency>
4) update logback.xml having default pattern instead of cyan
https://github.com/qaprosoft/carina-demo/blob/14f7f7a7c426b1c6d86768abddf4c6467b32b016/src/main/resources/logback.xml#L15

**Comment by vdelendik** [comment]
default log pattern is
`<pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>`

**Comment by ivansnytko** [comment]
Execute api/web tests over carina-demo:
log messages displayed for INFO layer
no DEBUG messages
tests executed as usual

**Comment by okamara** [comment]
@ivansnytko could you please add carina-core_version= for verification this ticket?

**Comment by okamara** [comment]
Tested. Fixed.
